from django.urls import path
from .views import (
    AboutAPIView,
    CultureListAPIView,
    DestinationDetailAPIView,
    DestinationListAPIView,
    DestinationRoutesAPIView,
    FAQListAPIView,
    FilterMetaAPIView,
    HomeAPIView,
    MapDestinationAPIView,
    NearbyPlacesAPIView,
    RegionDetailAPIView,
    RegionListAPIView,
    RouteGuideDetailAPIView,
    RouteGuideListAPIView,
    SearchGlobalAPIView,
    SearchSuggestionAPIView,
    SEOMetaAPIView,
    SocialMediaAPIView,
)

app_name = 'main'

urlpatterns = [
    path('home/', HomeAPIView.as_view(), name='home'),
    path('about/', AboutAPIView.as_view(), name='about'),
    path('culture/', CultureListAPIView.as_view(), name='culture-list'),
    path('madaniyat/', CultureListAPIView.as_view(), name='madaniyat-list'),
    path('places/', DestinationListAPIView.as_view(), name='place-list'),
    path('places/nearby/', NearbyPlacesAPIView.as_view(), name='places-nearby'),
    path('places/<slug:slug>/', DestinationDetailAPIView.as_view(), name='place-detail'),
    path('places/<slug:slug>/routes/', DestinationRoutesAPIView.as_view(), name='place-routes'),
    path('routes/', RouteGuideListAPIView.as_view(), name='route-list'),
    path('routes/<uuid:id>/', RouteGuideDetailAPIView.as_view(), name='route-detail'),
    path('regions/', RegionListAPIView.as_view(), name='region-list'),
    path('regions/<slug:slug>/', RegionDetailAPIView.as_view(), name='region-detail'),
    path('map/places/', MapDestinationAPIView.as_view(), name='map-places'),
    path('faqs/', FAQListAPIView.as_view(), name='faq-list'),
    path('search/suggestions/', SearchSuggestionAPIView.as_view(), name='search-suggestions'),
    path('search/global/', SearchGlobalAPIView.as_view(), name='search-global'),
    path('meta/filters/', FilterMetaAPIView.as_view(), name='meta-filters'),
    path('seo/meta/', SEOMetaAPIView.as_view(), name='seo-meta'),
    path('social-media/', SocialMediaAPIView.as_view(), name='social-media'),
]
