# Generated by Django 6.0 on 2026-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeguide',
            name='duration_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Davomiyligi'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='duration_text_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Davomiyligi'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='duration_text_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Davomiyligi'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='duration_text_uz',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Davomiyligi'),
        ),
    ]
