# Generated by Django 6.0 on 2026-04-05 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_routeguide_duration_text_routeguide_duration_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Tavsiya etilgan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['created_at'],
            },
        ),
    ]
