# Generated by Django 6.0 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_socialmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuzbekistan",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="Video havolasi"),
        ),
    ]
