# Generated by Django 6.0 on 2026-04-08 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_aboutuzbekistan_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUzbekistanVideo",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqt")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqt")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Faol")),
                ("is_featured", models.BooleanField(db_index=True, default=False, verbose_name="Tavsiya etilgan")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Tartib raqami")),
                ("title", models.CharField(blank=True, max_length=180, verbose_name="Video sarlavhasi")),
                ("url", models.URLField(verbose_name="Video havolasi")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="homepage/videos/", verbose_name="Video preview rasmi"),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="main.aboutuzbekistan",
                        verbose_name="About bo'limi",
                    ),
                ),
            ],
            options={
                "verbose_name": "About video",
                "verbose_name_plural": "About videolar",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
