# Generated by Django 6.0 on 2026-04-08 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_aboutuzbekistanvideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqt")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqt")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Faol")),
                ("is_featured", models.BooleanField(db_index=True, default=False, verbose_name="Tavsiya etilgan")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Tartib raqami")),
                ("title", models.CharField(max_length=180, verbose_name="Sarlavha")),
                ("title_uz", models.CharField(max_length=180, null=True, verbose_name="Sarlavha")),
                ("title_ru", models.CharField(max_length=180, null=True, verbose_name="Sarlavha")),
                ("title_en", models.CharField(max_length=180, null=True, verbose_name="Sarlavha")),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True, verbose_name="Slug")),
                ("short_description", models.CharField(blank=True, max_length=255, verbose_name="Qisqa tavsif")),
                ("short_description_uz", models.CharField(blank=True, max_length=255, null=True, verbose_name="Qisqa tavsif")),
                ("short_description_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="Qisqa tavsif")),
                ("short_description_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="Qisqa tavsif")),
                ("image", models.ImageField(upload_to="culture/items/", verbose_name="Rasm")),
                ("detail_url", models.URLField(blank=True, verbose_name="Batafsil havola")),
            ],
            options={
                "verbose_name": "Madaniyat elementi",
                "verbose_name_plural": "Madaniyat elementlari",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
