# Generated by Django 6.0 on 2026-04-26 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_cultureitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqt")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqt")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Faol")),
                ("is_featured", models.BooleanField(db_index=True, default=False, verbose_name="Tavsiya etilgan")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Tartib raqami")),
                ("title", models.CharField(max_length=220, verbose_name="Sarlavha")),
                ("title_uz", models.CharField(max_length=220, null=True, verbose_name="Sarlavha")),
                ("title_ru", models.CharField(max_length=220, null=True, verbose_name="Sarlavha")),
                ("title_en", models.CharField(max_length=220, null=True, verbose_name="Sarlavha")),
                ("subtitle", models.CharField(blank=True, max_length=300, verbose_name="Tagline")),
                ("subtitle_uz", models.CharField(blank=True, max_length=300, null=True, verbose_name="Tagline")),
                ("subtitle_ru", models.CharField(blank=True, max_length=300, null=True, verbose_name="Tagline")),
                ("subtitle_en", models.CharField(blank=True, max_length=300, null=True, verbose_name="Tagline")),
                ("cta_primary_label", models.CharField(default="Joylarni ko'rish", max_length=80, verbose_name="Asosiy tugma matni")),
                ("cta_primary_label_uz", models.CharField(max_length=80, null=True, verbose_name="Asosiy tugma matni")),
                ("cta_primary_label_ru", models.CharField(max_length=80, null=True, verbose_name="Asosiy tugma matni")),
                ("cta_primary_label_en", models.CharField(max_length=80, null=True, verbose_name="Asosiy tugma matni")),
                ("cta_primary_url", models.CharField(default="/places/", max_length=255, verbose_name="Asosiy tugma havolasi")),
                ("cta_secondary_label", models.CharField(default="Xaritada ko'rish", max_length=80, verbose_name="Ikkinchi tugma matni")),
                ("cta_secondary_label_uz", models.CharField(max_length=80, null=True, verbose_name="Ikkinchi tugma matni")),
                ("cta_secondary_label_ru", models.CharField(max_length=80, null=True, verbose_name="Ikkinchi tugma matni")),
                ("cta_secondary_label_en", models.CharField(max_length=80, null=True, verbose_name="Ikkinchi tugma matni")),
                ("cta_secondary_url", models.CharField(default="/map/", max_length=255, verbose_name="Ikkinchi tugma havolasi")),
                ("featured_image", models.ImageField(blank=True, null=True, upload_to="homepage/banner/", verbose_name="Banner rasmi")),
                ("media_file", models.FileField(blank=True, null=True, upload_to="homepage/banner/media/", verbose_name="Banner media fayli")),
                ("media_url", models.URLField(blank=True, verbose_name="Banner media havolasi")),
            ],
            options={
                "verbose_name": "Bosh sahifa banneri",
                "verbose_name_plural": "Bosh sahifa bannerlari",
                "ordering": ["-is_featured", "sort_order", "created_at"],
            },
        ),
    ]
